"""Top-level package for rag2f."""

# Expose version information when available (generated by setuptools-scm)
try:
    from ._version import __commit__, __dirty__, __distance__, __version__
except ImportError:  # pragma: no cover
    __version__ = "unknown"
    __commit__ = "unknown"
    __distance__ = 0
    __dirty__ = False

__all__ = ["core", "__version__", "__commit__", "__distance__", "__dirty__"]
